services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./livekit/livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml

  backend:
    image: novikov551/together-backend:latest
    container_name: together-backend
    restart: unless-stopped
    ports:
      - "5163:5163"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LiveKit__WebSocketUrl=ws://localhost:7880
      - LiveKitConfig__HttpUrl=http://host.docker.internal:7880
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - livekit

  frontend:
    image: novikov551/together-frontend:latest
    container_name: together-frontend
    restart: unless-stopped
    ports:
      - "8443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/letsencrypt/live/together-friends.duckdns.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/together-friends.duckdns.org/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - backend
