services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./livekit/livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml

  backend:
    image: novikov551/together-backend:latest
    container_name: together-backend
    restart: unless-stopped
    ports:
      - "5163:5163"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LiveKit__WebSocketUrl=ws://localhost:7880
      - LiveKitConfig__HttpUrl=http://host.docker.internal:7880
      - LiveKitConfig__ApiKey=apikey
      - LiveKitConfig__ApiSecret=AS1234DFAS1246DF1sdgsedthy5TO6TRgdfsgf443455
      - Jwt__Secret=sDf8Kj2Lp9Qw5RtXz7Uy3Vn4Bm6Nc8EaG1hJ2kL3mN4oP5qR6sT7uV8wX9yZ0
      - AdminProfile__user_name=family
      - AdminProfile__password=F@m1ly_C4ll_2025!
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - livekit

  frontend:
    image: novikov551/together-frontend:latest
    container_name: together-frontend
    restart: unless-stopped
    ports:
      - "8443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/letsencrypt/live/together-friends.duckdns.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/together-friends.duckdns.org/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - backend
